# Generated by Django 3.2.9 on 2021-11-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0004_alter_embed_last_modification_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embed',
            old_name='embed_url',
            new_name='event_url',
        ),
        migrations.AddField(
            model_name='embed',
            name='title',
            field=models.CharField(default='Evento Sin Nombre 2021-11-10 04:34:45.901748', max_length=200),
        ),
        migrations.AddField(
            model_name='modification',
            name='new_title',
            field=models.CharField(default='Evento Sin Nombre 2021-11-10 04:34:45.958137', max_length=200),
        ),
        migrations.AddField(
            model_name='modification',
            name='previous_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_name', to='embeds.embed'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(1, 'YouTube'), (2, 'Vimeo')]),
        ),
    ]
