# Generated by Django 3.2.9 on 2021-11-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0005_auto_20211110_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='platform',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Vimeo', 'Vimeo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='embed',
            name='title',
            field=models.CharField(default='Evento Sin Nombre 2021-11-10 04:49:13.543943', max_length=200),
        ),
        migrations.AlterField(
            model_name='modification',
            name='new_title',
            field=models.CharField(default='Evento Sin Nombre 2021-11-10 04:49:13.596748', max_length=200),
        ),
    ]
